<?php 
return [
'cnf_appname' 			=> 'Katana Project',
'cnf_appdesc' 			=> 'PHP Application Builder',
'cnf_comname' 			=> 'EcuaSolutions',
'cnf_email' 			=> 'info@ecuasolutions.com',
'cnf_metakey' 			=> 'my site , my company ',
'cnf_metadesc' 		=> 'Write description for your site',
'cnf_group' 			=> '3',
'cnf_activation' 		=> 'manual',
'cnf_multilang' 		=> '1',
'cnf_lang' 			=> 'es',
'cnf_regist' 			=> 'true',
'cnf_front' 			=> 'false',
'cnf_recaptcha' 		=> 'false',
'cnf_theme' 			=> 'default',
'cnf_backend' 			=> 'minimal',
'cnf_recaptchapublickey' => '6LeA3EMUAAAAAHrXpgF2qc7b5dUOIoW0izy91SAG',
'cnf_recaptchaprivatekey' => '6LeA3EMUAAAAAGLIWJwjoNl1R8yXPZf2ME5Hv85s',
'cnf_mode' 			=> 'production',
'cnf_logo' 			=> 'backend-logo.png',
'cnf_allowip' 			=> '',
'cnf_restrictip' 		=> '192.116.134 , 194.111.606.21 ',
'cnf_mail' 			=> 'swift',
'cnf_maps' 			=> 'AIzaSyAayRr-0yZ1ejGGX6l--XDVbHWU85wPj9U',
'cnf_date' 			=> 'Y-m-d',
];
